repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: no-commit-to-branch
- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
  hooks:
  - id: php-lint
  - id: php-cs-fixer
    files: \.(php)$
    args: [--level=PSR12]
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: 'v7.27.0'  # Use the sha / tag you want to point at
  hooks:
  - id: eslint
    additional_dependencies:
      - eslint-config-airbnb-base@^14.2.1
      - eslint-plugin-import@^2.23.4
      - eslint@^7.27.0
