name: Release Plugin

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zipping
        run: |
          zip elementor-slider-addon.zip assets/ widgets/ elementor-slider-addon.php
      - name: Generate Changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Changelog
        run: echo ${{ steps.generate_changelog.outputs.body }} > ${{ github.workflow }}-CHANGELOG.txt
        run: echo ${{ steps.generate_changelog.outputs.tag_name }} > ${{ github.workflow }}-CHANGELOG.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: ${{ github.workflow }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workflow }}-CHANGELOG.txt
          files: elementor-slider-addon.zip
          tag_name: ${{ steps.generate_changelog.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
